apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chart-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: chart

  source:
    repoURL: https://github.com/Eugentk/argocd-demo.git
    targetRevision: main
    path: chart/demo

    helm:
      parameters:
      - name: "service.port"
        value: "8082"

      valueFiles:
      - values-dev.yaml

      values: |
        # replicaCount: 2
        serviceAccount:
          create: true
          annotations:
            demo/role: demo-annotation
          name: sa-custom-name

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true