apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-argo-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
 
  source:
    repoURL: https://github.com/Eugentk/argocd-demo.git
    targetRevision: main
    path: demo
  destination: 
    server: https://kubernetes.default.svc
    namespace: demo
 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true


