apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ingress
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for Mobidev Demo
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'